# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protos import mapb_pb2 as mapb__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in mapb_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class manageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.connect = channel.unary_unary(
                '/mapb.manageService/connect',
                request_serializer=mapb__pb2.Empty.SerializeToString,
                response_deserializer=mapb__pb2.CliInfo.FromString,
                _registered_method=True)
        self.changeServer = channel.unary_unary(
                '/mapb.manageService/changeServer',
                request_serializer=mapb__pb2.CliChange.SerializeToString,
                response_deserializer=mapb__pb2.Empty.FromString,
                _registered_method=True)
        self.changeServerRandom = channel.unary_unary(
                '/mapb.manageService/changeServerRandom',
                request_serializer=mapb__pb2.CliId.SerializeToString,
                response_deserializer=mapb__pb2.ChangeInfo.FromString,
                _registered_method=True)
        self.disconnect = channel.unary_unary(
                '/mapb.manageService/disconnect',
                request_serializer=mapb__pb2.CliId.SerializeToString,
                response_deserializer=mapb__pb2.Empty.FromString,
                _registered_method=True)
        self.online = channel.unary_unary(
                '/mapb.manageService/online',
                request_serializer=mapb__pb2.SerRequest.SerializeToString,
                response_deserializer=mapb__pb2.SerInfo.FromString,
                _registered_method=True)
        self.offline = channel.unary_unary(
                '/mapb.manageService/offline',
                request_serializer=mapb__pb2.SerInfo.SerializeToString,
                response_deserializer=mapb__pb2.Empty.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/mapb.manageService/Get',
                request_serializer=mapb__pb2.Request.SerializeToString,
                response_deserializer=mapb__pb2.Response.FromString,
                _registered_method=True)
        self.Put = channel.unary_unary(
                '/mapb.manageService/Put',
                request_serializer=mapb__pb2.KV.SerializeToString,
                response_deserializer=mapb__pb2.Response.FromString,
                _registered_method=True)
        self.Del = channel.unary_unary(
                '/mapb.manageService/Del',
                request_serializer=mapb__pb2.Request.SerializeToString,
                response_deserializer=mapb__pb2.Response.FromString,
                _registered_method=True)


class manageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def connect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def changeServer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def changeServerRandom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def disconnect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def online(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def offline(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Put(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Del(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_manageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'connect': grpc.unary_unary_rpc_method_handler(
                    servicer.connect,
                    request_deserializer=mapb__pb2.Empty.FromString,
                    response_serializer=mapb__pb2.CliInfo.SerializeToString,
            ),
            'changeServer': grpc.unary_unary_rpc_method_handler(
                    servicer.changeServer,
                    request_deserializer=mapb__pb2.CliChange.FromString,
                    response_serializer=mapb__pb2.Empty.SerializeToString,
            ),
            'changeServerRandom': grpc.unary_unary_rpc_method_handler(
                    servicer.changeServerRandom,
                    request_deserializer=mapb__pb2.CliId.FromString,
                    response_serializer=mapb__pb2.ChangeInfo.SerializeToString,
            ),
            'disconnect': grpc.unary_unary_rpc_method_handler(
                    servicer.disconnect,
                    request_deserializer=mapb__pb2.CliId.FromString,
                    response_serializer=mapb__pb2.Empty.SerializeToString,
            ),
            'online': grpc.unary_unary_rpc_method_handler(
                    servicer.online,
                    request_deserializer=mapb__pb2.SerRequest.FromString,
                    response_serializer=mapb__pb2.SerInfo.SerializeToString,
            ),
            'offline': grpc.unary_unary_rpc_method_handler(
                    servicer.offline,
                    request_deserializer=mapb__pb2.SerInfo.FromString,
                    response_serializer=mapb__pb2.Empty.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=mapb__pb2.Request.FromString,
                    response_serializer=mapb__pb2.Response.SerializeToString,
            ),
            'Put': grpc.unary_unary_rpc_method_handler(
                    servicer.Put,
                    request_deserializer=mapb__pb2.KV.FromString,
                    response_serializer=mapb__pb2.Response.SerializeToString,
            ),
            'Del': grpc.unary_unary_rpc_method_handler(
                    servicer.Del,
                    request_deserializer=mapb__pb2.Request.FromString,
                    response_serializer=mapb__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mapb.manageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mapb.manageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class manageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def connect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mapb.manageService/connect',
            mapb__pb2.Empty.SerializeToString,
            mapb__pb2.CliInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def changeServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mapb.manageService/changeServer',
            mapb__pb2.CliChange.SerializeToString,
            mapb__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def changeServerRandom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mapb.manageService/changeServerRandom',
            mapb__pb2.CliId.SerializeToString,
            mapb__pb2.ChangeInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def disconnect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mapb.manageService/disconnect',
            mapb__pb2.CliId.SerializeToString,
            mapb__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def online(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mapb.manageService/online',
            mapb__pb2.SerRequest.SerializeToString,
            mapb__pb2.SerInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def offline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mapb.manageService/offline',
            mapb__pb2.SerInfo.SerializeToString,
            mapb__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mapb.manageService/Get',
            mapb__pb2.Request.SerializeToString,
            mapb__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Put(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mapb.manageService/Put',
            mapb__pb2.KV.SerializeToString,
            mapb__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Del(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mapb.manageService/Del',
            mapb__pb2.Request.SerializeToString,
            mapb__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
